### PR TITLE
Get rid of warnings about defined constant

### LINKED ISSUE #71: Warning: already initialized constant Module::URL_MAP
Hey we keep getting warnings about `already initialized constant Module::URL_MAP` can you change it so that you only create the constant unless it is already defined?

### PR DESCRIPTION
**Pull request by mhenrixon**
Close #71

### CODE REVIEW

**Comment by martinb3** [comment]
:+1:

**Comment by chilicheech** [comment]
:+1:

**Comment by rmoriz** [comment]
:+1:
very annoying in ChefSpec runs…

**Comment by rmoriz** [comment]
Anything I can help with so this gets merged and released?

**Pull request merged**
