### PR TITLE
Added Windows Support

### PR DESCRIPTION
**Pull request by Stromweld**
We've been running a fork with this added code for 6 months on both linux and windows. Chef clients have upgraded as expected every time. 

Due to the latest updates from HW I reforked this repo and reapplied my changes so as to not conflict with the recent updates.

### CODE REVIEW

**Comment by Stromweld** [comment]
This should take care of pull requests #57, #67, and #88 as well as issue #32

**Comment by luckymike** [comment]
Thanks for the updated PR!

**Comment by jptoto** [comment]
:+1:

**Comment by jptoto** [comment]
I did a quick review of the commit and it looks solid. Would be _awesome_ to have this merged and pushed to Supermarket soon!

**Comment by luckymike** [comment]
I'd like to run these through test-kitchen, and add windows as a platform in the `.kitchen.yml`

The [setup is a little involved](http://kitchen.ci/blog/test-kitchen-windows-test-flight-with-vagrant/), so I'll do it as soon as I have a free hour or two. If someone beats me to it, all the better.

**Comment by jptoto** [comment]
@luckymike  Fair enough! Test Kitchen in Windows _IS_ a little more involved but I've got some local vagrant / test kitchen action so I'll try and run this ASAP myself as well. I'll report back if I can get it done. Cheers!

**Comment by Stromweld** [comment]
Yeah I'm fairly new to chef and ruby and haven't fully figured out test kitchen especially in windows yet. I usually test by knifing a new server aws against my dev account then work out the kinks and publish to our production chef-server when ready.

**Comment by luckymike** [comment]
I was able to run the current test suites to confirm no regressions to tested resources. I added what should be an equivalent windows platform and the converge failed:

https://gist.github.com/luckymike/814b66f4b470990dbbff

@Stromweld are you setting any additional attributes via a role, wrapper cookbook, or environment in your working setup? Do you have anything configured in your client.rb that might result in non-default behavior in the Chef run?

**Comment by Stromweld** [comment]
we do have some attributes set in a base wrapper cookbook that we use for all windows machines and we set:
node.default['omnibus_updater']['prevent_downgrade'] = true
node.default['omnibus_updater']['force_latest'] = true
node.default['omnibus_updater']['restart_chef_service'] = true

Looking at the code I'm not totally sure why ours works though. Looking at your gist a simple fix for the windows_package resource would be to change remote_path variable to File.join(node[:omnibus_updater][:cache_dir], File.basename(remote_path)). I'm currently spinning up a VM and testing this cookbook without anything else in the runlist. If successful I'll commit the change to this PR.

**Comment by Stromweld** [comment]
Here is the fix in place. The below gist is the output from the chef-client runs. When the installer kicks off it does send SIGINT to the current running process chef throws an error about process exit. Subsequent chef-client run in the output you can see is the updated version of chef-client.

https://gist.github.com/Stromweld/4ee67970b0a567443f39

**Comment by luckymike** [comment]
I'm still running into that error on every converge in test-kitchen. Which windows server version are you using, and have you been able to converge successfully the first time, or only after failing first?

**Comment by Stromweld** [comment]
I'm testing on Windows server 2012 r2. It always throws that error during the install step as the installer calls the current chef run to exit. I've been testing adding ignore_failure true to the Windows package as well and it'll let the chef client finish after the exit error but the client does get updated. It'd be like enabling the kill chef attribute that causes chef client to raise an exception and stop the current chef run after update. Just not sure how to get around that on Windows installer.

**Comment by Stromweld** [comment]
Looking at msiexec that is used to install the msi package I haven't found an option or anything that would cause it to suppress the sigint exit signal. When running chef-client as a service the run that updates the client throws the error but completes the install and then the next scheduled run is on the new client version and converges correctly.

**Comment by webframp** [comment]
This threw an error for me as well on Windows 7:

```
Recipe: omnibus_updater::installer
  * windows_package[Chef Client v12.7.2] action install

    ================================================================================
    Error executing action `install` on resource 'windows_package[Chef Client v12.7.2]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1603'
    ---- Begin output of msiexec /qn /i "c:\chef\cache\omnibus_updater\chef-client-12.7.2-1-x86.msi"  ----
    STDOUT:
    STDERR:
    ---- End output of msiexec /qn /i "c:\chef\cache\omnibus_updater\chef-client-12.7.2-1-x86.msi"  ----
    Ran msiexec /qn /i "c:\chef\cache\omnibus_updater\chef-client-12.7.2-1-x86.msi"  returned 1603

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/omnibus_updater/recipes/installer.rb

     26:   windows_package "Chef Client v#{version}" do
     27:     source File.join(node[:omnibus_updater][:cache_dir], File.basename(remote_path))
     28:   end
     29: else

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/omnibus_updater/recipes/installer.rb:26:in `from_file'

    windows_package("Chef Client v12.7.2") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "Chef Client v12.7.2"
      version "12.7.2.1"
      timeout 600
      source "c:\\chef\\cache\\omnibus_updater\\chef-client-12.7.2-1-x86.msi"
      returns [0]
      declared_type :windows_package
      cookbook_name "omnibus_updater"
      recipe_name "installer"
    end


Running handlers:
Running handlers complete
Chef Client failed. 2 resources updated in 01 minutes 20 seconds
```

**Comment by Stromweld** [comment]
What version of chef client did you have prior to chef trying to update it? I ran into the same issue when I ran this cookbook on a machine with chef 12.6.0. The msiexec program would uninstall chef but runs into access denied error trying to remove some files in c:\opscode\embeddded\.... But in my testing 12.5.1 and 11.14.6 etc... have not had the issue. Googling I found there was a similar issue with the msi installer back in 2014 after MS released a patch. Later MS released another patch that fixed the issue.

**Comment by Stromweld** [comment]
@luckymike Have you had any better luck testing? Any suggestions for me on where to go from here?

**Comment by webframp** [comment]
Yea it was from 12.6.0

**Comment by luckymike** [comment]
I've had the same error every single time. I haven't admined a Windows server since 2000, so I'm afraid I won't be much help in diagnosing how to adjust things for Windows.

**Comment by webframp** [comment]
So, if this is a known problem with upgrading a chef install from 12.6.0 to anything higher I'd say this is incomplete. It either needs to work everywhere or fail safely. In my case it left a broken local chef client install, which would be very annoying for anyone trying to this in production. We can't exactly have a cookbook that fails chef runs some of the time.

@Stromweld Any thoughts on why it fails based on what you've seen so far?

**Comment by Stromweld** [comment]
when manually running the chef client on the node and it hits the upgrade step I see a seperate command line box open up that executest the msiexec command for the install. While it's running you see it going through the uninstall process and gets access denied errors on several files under c:\opscode\embedded\. Then it finishes up the uninstall step and throws the error and stops. Doesn't execute the install. I wouldn't say it's a chef or cookbook issue as I would either a windows or msi package issue. You can see this reference when this happened before due to a bad patch windows released. https://github.com/chef-cookbooks/windows/issues/130 later a subsequent windows patch release fixed it. I have verified the test systems I've been running are fully patched.

**Comment by Stromweld** [comment]
So far I have only found this particular issue only on clients with 12.6.0. I've tested a few other older clients with the upgrade and this hasn't been an issue. I'm thinking of looking at possibly running the installer inside a seperate powershell script to possibly get around this issue and the sigint exit command that's sent to chef client when an upgrade succeeds but stops chef from fully converging.

**Comment by Stromweld** [comment]
looking again at that issue I linked, codesilverback mentions "The chef bootstrapper uses a workaround of creating a scheduled task to run the installer, and that seems to work, but wow. What a hack!" and this cookbook is using that method as well, https://github.com/biola/chef-omnibus_updater_windows/blob/master/recipes/installer.rb. Could do it this way too.

**Comment by Stromweld** [comment]
ok this process has worked and fully converges without errors on first run for updating chef clients 11.14.6 and 12.5.1. Still have to test 12.6.0 and updating with service running.

**Comment by Stromweld** [comment]
Ok so this latest commit I have tested clients 11.14.6, 12.5.1 and confirmed working whether manual chef-client run or it's ran and updated as a service. No errors, etc... Very hacky though but keeps install process in the chef-client run instead of outside in a scheduled task etc...

Something is wrong with windows uninstaller for 12.6.0 though. No matter how I run uninstall it leaves locked files behind in c:\opscode\embedded\ and then the install step fails with 1603 error due to access being denied on those files. Tomorrow I'll try bootstrapping a fresh 12.6.0 node and test my updates to the cookbook some more.

**Comment by Stromweld** [comment]
Also added attribute to specify ADDLOCAL parameter to msiexec and set default to install chef-client and chef-client service with a comment recommending adding chef powershell modules for clients about 12.4.0.

**Comment by Stromweld** [comment]
For the life of me I have not been able to come up with a work around for the 12.6.0 upgrade. There is something really weird in windows with that version of chef installed. I've tried adding command line commands to remove the left over files after the uninstall step, I've tried changing permissions and ownership to be able to remove the files and all attempts for the past 2 days have resulted in access denied on the files during the chef client run and then the install of the updated client fails due to the files stuck there. I can manually browse to the files and remove them after the chef client run fails so I don't know what's going on. Files even throw access denied when I use the force flag with the delete command.

Testing with older version of the chef client older than 12.6.0 have worked fine though. @luckymike can you try your test kitchen test again?

**Comment by luckymike** [comment]
Yes, I'll try the test kitchen run this afternoon, I hope. Can you open an issue with Chef about the 12.6.0 failures?

**Comment by Stromweld** [comment]
Yeah I'll open the issue with chef.

**Comment by Stromweld** [comment]
issue opened https://github.com/chef/chef/issues/4623 for the 12.6.0 update failure

**Comment by luckymike** [comment]
:+1: Tested with `default[:omnibus_updater][:version] = '12.5.1'` and it worked!

**Comment by Stromweld** [comment]
Sweet. Anybody have any code comments and or suggestions? I'm still fairly new to ruby, chef, and programming in general so definitely open to feedback.

**Comment by luckymike** [comment]
Confirmed no regressions as well :)

**Comment by cpoole** [comment]
Anecdotal but your fork worked on a Windows Server 2008 node to upgrade from 11.12 to 12.5.1, only chef_client was installed and updated though, chef service is not installed on that node. I can test a number of other nodes if needed

**Comment by Stromweld** [comment]
Yeah that'd be great. The more testing the better.

**Comment by luckymike** [comment]
Note, this passes the tests in #104

**Comment by Stromweld** [comment]
What do you guys think about getting this code merged to develop and adding a note in the readme about the 12.6.0 upgrade issue?

**Comment by luckymike** [comment]
Yep, I'm leaning that direction.

**Comment by cpoole** [comment]
What about a catch in the default.rb recipe to halt the cookbook if it detects 12.6.0 is installed? that way you don't bork your install if you don't read the documentation. 

i think checking node['chef_packages']['chef']['version'] would be able to determine that.

**Comment by luckymike** [comment]
@cpoole My concern with that approach is the longterm maintainability. We don't really have a way of knowing if this bug/issue will continue to exist with future versions. It may or may not be fixed in 12.6.1 or 12.7.0, etc, so that catch may or may not protect operators upgrading beyond 12.6.0. If we take a pessimistic view, and exit on `>= 12.6.0`, then we risk exiting with versions that don't have this issue.

Beyond noting known issues, we can't take responsibility for errors introduced by Chef. I'm happy to include a node in both the Changelog and the Read Me warning Windows users. 

As this is the first introduction of Windows support in this cookbook, there shouldn't be anyone out there using this already who will be bit by a surprise.

**Comment by webframp** [comment]
It was mentioned that a specific patch fixed the issue? Has that been tested further?

If we know the kb number maybe it would be possible to query for it and provide a safeguard?

If kb_installed? && installed_chef_client_is_12.6.0

A query example is here:

https://github.com/criteo-cookbooks/ms_dotnet/blob/master/attributes/ms_dotnet4.rb

See the end of the attributes, around 4.5.2 attribute setting

**Comment by Stromweld** [comment]
In the past a specific kb patch introduced a similar error. We have to confirmed that is the case this time or what kb it may be. But I think instead of a catch for >= 12.6.0 a catch for == 12.6.0 is reasonable since the uninstall step will run otherwise and then the install may fail leaving a chef-client without chef installed. We don't however know if the issue still exists or not with 12.7.2 since there is nothing higher to upgrade to yet.

**Comment by cpoole** [comment]
In case we do want to proceed with the catch, here is what it looks like in action. Not super graceful, but it works. 

`[2016-03-01T19:27:47-08:00] INFO: *** Chef 12.6.0 ***
[2016-03-01T19:27:47-08:00] INFO: Chef-client pid: 15140
[2016-03-01T19:27:57-08:00] INFO: Run List is [role[role_bamboo], role[test_role]]
[2016-03-01T19:27:57-08:00] INFO: Run List expands to [omnibus_updater]
[2016-03-01T19:27:57-08:00] INFO: Starting Chef Run for <redacted>
[2016-03-01T19:27:57-08:00] INFO: Running start handlers
[2016-03-01T19:27:57-08:00] INFO: Start handlers complete.
[2016-03-01T19:27:57-08:00] INFO: Loading cookbooks [omnibus_updater@1.0.7]
[2016-03-01T19:27:57-08:00] FATAL: Omnibus updater cannot upgrade or downgrade a Windows 12.6.0 installation
[0m
================================================================================[0m
[31mRecipe Compile Error in c:/chef-rm/cache/cookbooks/omnibus_updater/recipes/default.rb[0m
================================================================================[0m

[0mRuntimeError[0m
------------[0m
[0m

[0mCookbook Trace:[0m
---------------[0m
  c:/chef-rm/cache/cookbooks/omnibus_updater/recipes/default.rb:28:in `from_file'[0m

[0mRelevant File Content:[0m
----------------------[0m
c:/chef-rm/cache/cookbooks/omnibus_updater/recipes/default.rb:
[0m
[0m 21:    Chef::Log.warn 'Omnibus updater disabled via `disabled` attribute'
[0m 22:  elsif(node[:platform] == 'debian' && Gem::Version.new(node[:platform_version]) < Gem::Version.new('6.0.0'))
[0m 23:    Chef::Log.warn 'Omnibus updater does not support Debian 5'
[0m 24:  elsif(node[:platform] == 'raspbian')
[0m 25:    Chef::Log.warn 'Omnibus updater does not support Raspbian'
[0m 26:  elsif((node[:chef_packages][:chef][:version] == '12.6.0') && node[:os].downcase.include?('windows'))
[0m 27:    Chef::Log.fatal 'Omnibus updater cannot upgrade or downgrade a Windows 12.6.0 installation'
[0m 28>>   raise
[0m 29:  else
[0m 30:    include_recipe 'omnibus_updater::downloader'
[0m 31:    include_recipe 'omnibus_updater::installer'
[0m 32:  end
[0m 33:  
[0m 34:  if(node[:omnibus_updater][:remove_chef_system_gem])
[0m 35:    include_recipe 'omnibus_updater::remove_chef_system_gem'
[0m 36:  end
[0m 37:  [0m

[0m[2016-03-01T19:27:57-08:00] ERROR: Running exception handlers
[2016-03-01T19:27:57-08:00] ERROR: Exception handlers complete
[2016-03-01T19:27:57-08:00] INFO: Sending resource update report (run-id: 63c3890c-230e-4d11-8892-d06a75e3540e)
[2016-03-01T19:27:58-08:00] FATAL: Stacktrace dumped to c:/chef-rm/cache/chef-stacktrace.out
[2016-03-01T19:27:58-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-03-01T19:27:58-08:00] FATAL: RuntimeError: `

**Comment by Stromweld** [comment]
cpoole gave me this https://github.com/Stromweld/omnibus_updater/pull/1#issuecomment-191044186 pr adding the check to the default recipe. Let me know what you think and I can merge it in or leave it out.

**Comment by luckymike** [comment]
While I appreciate @cpoole's efforts, I really don't want us to go down the path of adding logic to route around Chef's bugs. If we include that, then we have to own it going forward, which becomes a maintenance headache for us, and encourages users to open issues here rather than with Chef's maintainers who should be responsible for prevention breaking changes between minor versions.

I do think we should note the known issue in the README and CHANGELOG, and we can also include example code for skipping the upgrade in case someone wants to implement it in a wrapper.

How does that sound?

**Comment by Stromweld** [comment]
That makes sense too, you guys are ultimately the primary maintainers so I'm cool with either way. I'll leave it as is.

**Comment by luckymike** [comment]
:+1: Merging! Thanks for your effort on this. I'll make the README and CHANGELOG updates directly in develop, b/c Github does not play great with merging .md changes.

**Comment by cpoole** [comment]
woohoo! thanks for the great work @Stromweld, the readme changes make me happy too :+1:

**Pull request merged**
