### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by alex-slynko**

### CODE REVIEW

**Comment by spuder** [comment]
+1 though windows 2012 R2 should also be supported

**Comment by luckymike** [comment]
Must target Develop for consideration.

**Comment by slyness** [comment]
@alex-slynko Please rebase this and adjust Pull Request to the develop branch instead of Master. Otherwise this PR will be closed. Thanks.

**Comment by luckymike** [comment]
We've got a tested Windows PR in #101, so I think this is deprecated anyway in favor of 101.

**Pull request closed without merging**
