### PR TITLE
Update Test Platforms

### PR DESCRIPTION
**Pull request by luckymike**
Remove Ubuntu 10.04 from test suites. Update Centos 5.8 to 5.11. Caveat vintage OS deployer.

Added Windows 2012 (Chef 12.5.1 and under only at this time)

### CODE REVIEW

**Comment by tas50** [comment]
Fully in support of removing 10.04, but there are a HUGE number of people on RHEL 5 still since it's supported for sometime.  That should get bumped to 5.11, but remain in place.

**Comment by luckymike** [comment]
@tas50 :+1: will adjust

**Comment by tas50** [comment]
I'm looking forward to the day RHEL 5 goes EOL

**Comment by luckymike** [comment]
Incorporated @tas50's changes from #83 as well.

**Comment by slyness** [comment]
Great. Thanks.

**Pull request merged**
