### PR TITLE
Get rid of warnings about defined constant

### LINKED ISSUE #71: Warning: already initialized constant Module::URL_MAP
Hey we keep getting warnings about `already initialized constant Module::URL_MAP` can you change it so that you only create the constant unless it is already defined?

### PR DESCRIPTION
**Pull request by mhenrixon**
close #71

### CODE REVIEW

**Comment by mhenrixon** [comment]
Can this please get some attention? It is really frustrating

**Comment by slyness** [comment]
@mhenrixon Thanks. I will look at this today. Sorry for the delay. I was on Vacation last week.

**Comment by slyness** [comment]
@mhenrixon on another note.. Can you please update this PR to be made against the `develop` branch instead of directly to `master`

**Comment by mhenrixon** [comment]
Closed in favor of #76

**Pull request closed without merging**
